repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        fail_fast: true
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0  # Use the latest release
    hooks:
      - id: codespell
        args: ["--skip=*.png,*.jpg,*.jpeg,*.gif", "--ignore-words-list=hte"]
        files: \.md$
        fail_fast: true
-   repo: local
    hooks:
      - id: dontet
        name: Dotnet Build
        language: system
        entry: dotnet build
        pass_filenames: false
        fail_fast: true
-   repo: local
    hooks:
      - id: sonar-scanner
        name: Run SonarScanner
        language: system
        entry: sonar-scanner
        pass_filenames: false
        fail_fast: true

