trigger:
  branches:
    include:
      - master
      - development

pool:
  vmImage: 'ubuntu-latest'

variables:
  isProd: $[eq(variables['Build.SourceBranchName'], 'master')]
  ACR_NAME: probuild
  ACR_IMAGE: $[eq(variables['Build.SourceBranchName'], 'master') ? 'probuild-backend' : 'qa-probuild-backend']
  AZURE_CONTAINER_APP: $[eq(variables['Build.SourceBranchName'], 'master') ? 'probuild-backend' : 'qa-probuild-backend']
  AZURE_RESOURCE_GROUP: rg-Probuild
  FRONTEND_URL: $[eq(variables['Build.SourceBranchName'], 'master') ? 'https://probuildai-ui.wonderfulgrass-0f331ae8.centralus.azurecontainerapps.io' : 'https://probuildai-backend-dev.wonderfulgrass-0f331ae8.centralus.azurecontainerapps.io']
  DOCKER_TAG: $[eq(variables['Build.SourceBranchName'], 'master') ? 'latest' : 'qa']
  ASPNETCORE_ENVIRONMENT: $[eq(variables['Build.SourceBranchName'], 'master') ? 'Production' : 'Staging']

stages:
- stage: BuildAndDeploy
  displayName: Build, Push Docker Image & Deploy to Azure Container Apps
  jobs:
  - job: BuildPushDeploy
    displayName: Build, Push, and Deploy Docker Image
    steps:

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
      displayName: Install Docker

    - task: AzureCLI@2
      displayName: Log in to Azure Container Registry
      inputs:
        azureSubscription: '$(AZURE_SUBCRIPTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(ACR_NAME)

    - task: Docker@2
      displayName: Build and push Docker image to ACR
      inputs:
        command: buildAndPush
        repository: $(ACR_NAME).azurecr.io/$(ACR_IMAGE)
        dockerfile: 'Dockerfile'
        tags: $(DOCKER_TAG)

    - task: AzureCLI@2
      displayName: Deploy to Azure Container Apps
      inputs:
        azureSubscription: '$(AZURE_SUBCRIPTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update \
            --name $(AZURE_CONTAINER_APP) \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --image $(ACR_NAME).azurecr.io/$(ACR_IMAGE):$(DOCKER_TAG) \
            --cpu 2 \
            --memory 4.0Gi \
            --env-vars \
              DB_CONNECTION_STRING="$(DB_CONNECTION_STRING)" \
              FRONTEND_URL="$(FRONTEND_URL)" \
              JWT_KEY="$(JWT_KEY)" \
              GPTAPIKEY="$(GPTAPIKEY)" \
              SENDGRID_API_KEY="$(SENDGRID_API_KEY)" \
              SENDGRID_EMAIL="$(SENDGRID_EMAIL)" \
              SENDGRID_FROM_EMAIL="$(SENDGRID_FROM_EMAIL)" \
              STRIPE_KEY="$(STRIPE_KEY)" \
              AZURE_BLOB_KEY="$(AZURE_BLOB_KEY)" \
              MapsAPI="$(MapsAPI)" \
              GeminiAPIKey="$(GeminiAPIKey)" \
              ASPNETCORE_ENVIRONMENT="$(ASPNETCORE_ENVIRONMENT)"
