using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProbuildBackend.Models
{
    public class TradePackage
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int JobId { get; set; }

        [ForeignKey("JobId")]
        public JobModel Job { get; set; }

        [Required]
        public string TradeName { get; set; }

        public string? Category { get; set; } // "Trade", "Vendor", "Supplier", "Equipment"

        public string? ScopeOfWork { get; set; }

        public decimal Budget { get; set; }

        public decimal LaborBudget { get; set; }

        public decimal MaterialBudget { get; set; }

        public decimal TotalBudget { get; set; }

        public decimal EffectiveBudget { get; set; }

        public string? Status { get; set; } // "Draft", "Posted", "Awarded"

        public decimal EstimatedManHours { get; set; }

        public decimal HourlyRate { get; set; }

        public string? EstimatedDuration { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? BidDeadline { get; set; }

        public string? LaborType { get; set; } // "Labor" | "Labor and Materials"

        public string? CsiCode { get; set; }

        public int? LinkedTradePackageId { get; set; }

        [ForeignKey("LinkedTradePackageId")]
        public TradePackage? LinkedTradePackage { get; set; }

        public bool IsAutoGenerated { get; set; }

        public bool IsInactive { get; set; }

        public bool IsHidden { get; set; }

        public string? SourceType { get; set; } // AI | USER | SYSTEM_LINKED

        public bool IsInHouse { get; set; }

        public bool PostedToMarketplace { get; set; }

        public DateTime? ArchivedAt { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
