name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Log in to Azure Container Registry using Admin User credentials
      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image to ACR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: probuild.azurecr.io/probuildai-backend:${{ github.sha }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: probuildai-backend
          images: probuild.azurecr.io/probuildai-backend:${{ github.sha }}
          slot-name: production  # Optional: Remove if not using slots
